# Build settings

name: Carann - Reclamemakers

markdown: redcarpet
permalink: pretty

url: /Carann

port: 4000

exclude: [
  'node_modules',
  'sass_cache',
  'Gruntfile.js',
  'package.json',
  'source']

collections:
  portfolio:
    output: true
    layout: entry
    permalink: /portfolio/:path/