# Build settings

name: Carann

markdown: redcarpet
permalink: pretty

url: /Carann

port: 4000

exclude: [
  'node_modules',
  'sass_cache',
  'Gruntfile.js',
  'package.json',
  'source']

collections:
- portfolio