# Build settings

name: Carann - Reclamemakers

markdown: kramdown
permalink: pretty

baseurl: http://localhost:4000

port: 4000

exclude: [
  'node_modules',
  'sass_cache',
  'grunt',
  'Gruntfile.js',
  'package.json',
  'source']

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/